# Generated by Django 4.1.3 on 2022-11-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.author')),
            ],
        ),
    ]
