# Generated by Django 4.1.3 on 2022-11-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_paintings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='Author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.author'),
        ),
        migrations.AlterField(
            model_name='paintings',
            name='image',
            field=models.ImageField(upload_to='./static/imgs/paintings', verbose_name=''),
        ),
    ]
